

/**
 * The factor by which the collision adjustment is reduced.
 */
export const COLLISION_LENIENCY = 0.3;

export const CAMERA_SPEED = 4;

export const BASIC_UNIT_SPEED = 2.0;
export const BASIC_UNIT_RANGE = 300;
export const BASIC_UNIT_BODY_SIZE = 32;
export const BASIC_UNIT_TURRET_LENGTH = 24;
export const BASIC_UNIT_HEALTH = 69;

export const LASER_DAMAGE = 0.5;

export const GRID_SCALE = 64;

export const DEFAULT_MAP = `.................................
..1.............1................
..1..............................
22...............................
.................................
.................................
.........0......0...0............
.................................
.................................
.................................
.................................
............0...0......0.........
.................................
.................................
.................................
.................................
................2................
.................................`
